# Generated by Django 5.1.7 on 2025-03-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='negative',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='positive',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
